services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6060:6060"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
# No shit sherlock, not including ollama here lol
